apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
  labels:
    app: frontend

spec:
  replicas: 1
  selector:
    matchlabels:
      app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
          - name: frontend
            image: anilkumarreddy/wanderlust-frontend:latest
            ports:
              - containerPort: 5173
        
---
apiVersion: v1
kind: Sevice
metadata:
  name: frontend-service 
  namespace: wanderlust
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 31000